#!/bin/python
"""
If n is odd, print Weird
If n is even and in the inclusive range of  to , print Not Weird
If n is even and in the inclusive range of  to , print Weird
If n is even and greater than , print Not Weird
source:  https://www.hackerrank.com/
"""

if __name__ == '__main__':
    n = int(raw_input().strip())
 
    if n % 2 == 0:
    
        if n>2 and n<=5:
            print("Not Weird")
        elif n>6 and n<=20:
            print("Weird")
        else:
            print("Not Weird")  
    else:
        print("Weird")





